server:
  slim:
    settings:
      displayErrorDetails: true

  router:
    routes:
      samples_list:
        path: /api/samples
        controller: Villermen\Soundboard\Controller\SamplesController
        action: listAction
        methods: [ get ]

      samples_get:
        path: /api/samples/{file:.+}
        controller: Villermen\Soundboard\Controller\SamplesController
        action: getAction
        methods: [ get ]

      index:
        path: /{path:.*}
        controller: Villermen\Soundboard\Controller\IndexController
        action: indexAction
        methods: [ get ]
